### ISSUE TITLE
Generate a site preview on pull requests 

### ISSUE THREAD

**Issue by LenzGr** [percona/community#197]
It would be nice to perform a build and generate a preview of the site including the changes proposed by a pull request. This ensures that the contribution does not accidentally break the site build and makes it easier to review the final result prior to merging a PR.

**Comment by dbazhenov** [comment]
I don't know how to implement it. 
It's enough to install Hugo locally when you make changes and check the site build locally.

**Comment by atymchuk** [comment]
Closed by https://github.com/percona/community/pull/316
