### ISSUE TITLE
Provide step-by-step instructions on how to submit a blog post

### ISSUE THREAD

**Issue by LenzGr** [percona/community#198]
The instructions provided in `CONTRIBUTING.md` are quite generic and assume a lot of prior knowledge with our platform. This may be quite a steep hurdle for new contributors that would be interested in contributing content, e.g. a blog post. It would be great to have some simple to follow step-by-step instructions on how to prepare and submit a blog post, for example.

**Comment by dbazhenov** [comment]
Done:
https://percona.community/blog/2022/02/10/how-to-publish-blog-post/
