### ISSUE TITLE
While hovering over card border radius is uneven on top and bottom.

### ISSUE THREAD

**Issue by devstardude** [percona/community#569]
While hovering over a card, the Top left and right don't show rounded corners like the bottom. It will be a great UI enhancement if the Border is evenly rounded on all four corners.

<img width="245" alt="image" src="https://user-images.githubusercontent.com/56074587/193472887-e1ddfb0d-be67-4d30-a02e-3c5704262ec3.png">

PS: @dbazhenov Can you please label it as 'hacktoberfest', I want to contribute to it.

**Comment by dbazhenov** [comment]
@devstardude please implement all 3 issues in one Pull Request, they are small, implemented through CSS in one file and are similar in theme.

**Comment by devstardude** [comment]
Alright ser, I'll make a PR soon.

**Comment by dbazhenov** [comment]
I expanded the Contributing.md section and added instructions on how to edit the design.
https://github.com/percona/community/blob/main/CONTRIBUTING.md#install-hugo-and-dev-environment
