### ISSUE TITLE
Card width does not match with image width when reducing portsize horizontally

### ISSUE THREAD

**Issue by devstardude** [percona/community#570]
It is a website Responsiveness Enhancement.
<img width="746" alt="image" src="https://user-images.githubusercontent.com/56074587/193473211-b8ef087b-35d1-42f2-a6e1-fbdf469b1f20.png">

@dbazhenov Can I work on this? please label it as 'hacktoberfest'. thanks.

**Comment by dbazhenov** [comment]
Yeah, I don't mind working on it, just make all the little improvements in one PR.

**Comment by dbazhenov** [comment]
If you need any help, please let me know.
