### ISSUE TITLE
There is no margin between cards when reducing portsize horizontally.

### ISSUE THREAD

**Issue by devstardude** [percona/community#571]
It is a good Responsiveness enhancement to have proper space between two cards at all port sizes.
<img width="752" alt="image" src="https://user-images.githubusercontent.com/56074587/193473333-66082d0d-b8ff-4855-a441-562d3a744158.png">

@dbazhenov Can I work on this?

**Comment by dbazhenov** [comment]
Yes, you can work on that, thanks for the idea.
