### ISSUE TITLE
Improving UI/UX with modern designs idea

### ISSUE THREAD

**Issue by anshu189** [percona/community#572]
Improving Website with some interactive as well as attractive with Minimalistic Modern Designs.

**Comment by dbazhenov** [comment]
Thank you for paying attention to the design, it is not clear what improvements we are talking about. Could you please tell us?

**Comment by anshu189** [comment]
By adding **Glassmorphism** effect on banners and improving the padding & margin of containers/cards to look even more minimal and unique.
As well as I noticed **there's a bug while hovering over the last navbar item**, the submenu is overflown from the main width of the body container. I'd like to fix that too.
If you assign me this task it would be a great opportunity to contribute to such a big community.

**Comment by dbazhenov** [comment]
Effects are not needed, we try to use JS as little as possible.
The site design will be redesigned in the near future in a different style, now the designers are working on it. 
I think there is no point in fixing non-critical errors right now.
