### ISSUE TITLE
Footer is overflowing in x-axis.

### ISSUE THREAD

**Issue by sarthakastic** [percona/community#574]

**Comment by dbazhenov** [comment]
Hi, Please, detail the task, attach screenshots

**Comment by sarthakastic** [comment]
The content in the footer section is horizontally scrollable and "about" is  not fully visible which makes the whole website overflow on the x-axis in the mobile view
<img width="1441" alt="Screenshot 2022-10-04 at 6 17 13 PM" src="https://user-images.githubusercontent.com/72138026/193824362-d2d6d241-5a71-47ac-9014-a5c21a273b9f.png">

**Comment by OyaleSalami** [comment]
Hello, want to assign me this task? I should have a PR by tomorrow

**Comment by dbazhenov** [comment]
@sarthakastic I agree, can you do a mobile menu?

**Comment by dbazhenov** [comment]
Dear @OyaleSalami Oyale this task was suggested by @sarthakastic, he has priority.

**Comment by sarthakastic** [comment]
@dbazhenov can u assign it to me under hacktoberfest label.

**Comment by dbazhenov** [comment]
I'll put a label on the PR

**Comment by sarthakastic** [comment]
okay

**Comment by dbazhenov** [comment]
https://github.com/percona/community/pull/588

**Comment by sarthakastic** [comment]
hey, can u pls add the hacktoberfest-accepted label?
