### ISSUE TITLE
Size of repo is quite large

### ISSUE THREAD

**Issue by slim-codes** [percona/community#607]
I just cloned this project in order to include my blog post in it and the size currently stands at approximately **800MB**.
This is quite large considering that I only need it to add my information and link to my post. 

- Firstly, I don't know if it's possible to compress repos. But if it is, it should be considered.
- Alternatively, consider creating a separate repo for adding stuff like blog posts, articles, docs etc. This is simply for convenience of cloning the project.

**Comment by dbazhenov** [comment]
Yes, I understand, I'm afraid the size of the repository has grown at the expense of blog images and events. 
We will consider reducing the size of the repository.

**Comment by LenzGr** [comment]
@slim-codes If you're just making a simple contribution, consider performing a [shallow clone](https://www.perforce.com/blog/vcs/git-beyond-basics-using-shallow-clones) instead of a full local clone of the repo. This significantly reduces the size of the local repo.

**Comment by slim-codes** [comment]
> @slim-codes If you're just making a simple contribution, consider performing a [shallow clone](https://www.perforce.com/blog/vcs/git-beyond-basics-using-shallow-clones) instead of a full local clone of the repo. This significantly reduces the size of the local repo.

WOW! this is interesting. I never knew that this was possible. There's still a lot I have to learn about git. 
Thanks a lot for this info

@dbazhenov  It'd be nice to include this info in the contribution guidelines as well. For those who don't know about it
