### ISSUE TITLE
Reduce font sizes on front page

### ISSUE THREAD

**Issue by jzb** [percona/community#685]
Can we reduce the font sizes and size of elements on the landing page in particular so that (for example) the "Welcome to Percona Community" fits in one line rather than two? The new design looks great but still looks really large.

**Comment by dbazhenov** [comment]
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/3863788/220350942-1ddda18a-a72e-427f-abfc-be637fedf286.png">

**Comment by dbazhenov** [comment]
Updated
