### ISSUE TITLE
Website: Events section: Change the display of authors

### ISSUE THREAD

**Issue by Aleksa-del** [percona/community#695]
Currently, In the posts published in the Events sections, speakers are displayed as authors of the text. It might be a bit confusing when the text author is not a speaker and writes about his experience at the event. Example: https://percona.community/events/prefosdem-2023/

My suggestion is to display the author of text, not speakers, there. Speakers will be displayed below the text as usual.

**Comment by dbazhenov** [comment]
https://github.com/percona/community/pull/696
